/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradlepro;

public class App {
﻿

public boolean isPalindrome(String input){
	if (input == null) {
throw new IllegalArgumentException("input shouldn't be null");
}


	if (input.equals(reverse(input))){
	return true;
	}
	Else {
	return false;
	}	
}

private String reverse(String input) {
	String rev = "";

	for (int i = input.length() - 1; i >= 0; i--) {
		re v= rev + input.charAt(i);
	}
	return rev;
}


}
