/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradlepro;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {


 	String input1 = "noon"; 
	App app = new App():
boolean expected = true; 
@Test
public void isPlaindromeTest()
{
	assertEquals(expected, app.isPalindrome(input1));
}
@Test
public void isNotPlaindrome Test()
{
	assertEquals(false, app.isPalindrome("abc"));
{

}
